<?php
require_once __DIR__ . '/../includes/layout.php';
require_any_role(['admin','incharge']);
$workload=fetch_all("SELECT t.Name,t.Department,t.Designation,COUNT(d.TTCDID) TotalLectures,COUNT(DISTINCT s.SubjectID) Subjects,COUNT(DISTINCT r.RoomID) Rooms FROM teacher t LEFT JOIN timetablecelldetail d ON d.TeacherID=t.TeacherID LEFT JOIN subject s ON s.SubjectID=d.SubjectID LEFT JOIN room r ON r.RoomID=d.RoomID GROUP BY t.TeacherID ORDER BY TotalLectures DESC,t.Name");
$rooms=fetch_all("SELECT r.Title,r.TTDName,COUNT(d.TTCDID) TotalBookings,COUNT(DISTINCT cell.PeriodID) UsedPeriods FROM room r LEFT JOIN timetablecelldetail d ON d.RoomID=r.RoomID LEFT JOIN timetablecell cell ON cell.TTCID=d.TTCID GROUP BY r.RoomID ORDER BY TotalBookings DESC");
$classes=fetch_all("SELECT c.Name,c.CurrentSemester,COUNT(d.TTCDID) TotalEntries FROM `class` c LEFT JOIN timetablecell cell ON cell.ClassID=c.ClassID LEFT JOIN timetablecelldetail d ON d.TTCID=cell.TTCID GROUP BY c.ClassID ORDER BY c.ClassID");
dashboard_start('Reports','Teacher workload, room utilization and class schedule summary');
?>
<div class="row g-3 mb-4"><?php stat_card('fa-chalkboard-teacher','Total Teachers',scalar_query('SELECT COUNT(*) FROM teacher'),'#7c3aed'); stat_card('fa-user-graduate','Total Students',scalar_query('SELECT COUNT(*) FROM student'),'#f59e0b'); stat_card('fa-calendar-check','Timetable Entries',scalar_query('SELECT COUNT(*) FROM timetablecelldetail'),'#059669'); stat_card('fa-door-open','Rooms',scalar_query('SELECT COUNT(*) FROM room'),'#2563eb'); ?></div>
<div class="data-card mb-4"><div class="d-flex justify-content-between mb-3 no-print"><h5 class="fw-bold">Teacher Workload Report</h5><button class="btn btn-outline-primary" onclick="window.print()"><i class="fa-solid fa-print me-1"></i>Print Reports</button></div><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Teacher</th><th>Department</th><th>Designation</th><th>Total Lectures</th><th>Subjects</th><th>Rooms Used</th></tr></thead><tbody><?php foreach($workload as $r): ?><tr><td><?= h($r['Name']) ?></td><td><?= h($r['Department']) ?></td><td><?= h($r['Designation']) ?></td><td><span class="badge text-bg-primary"><?= h($r['TotalLectures']) ?></span></td><td><?= h($r['Subjects']) ?></td><td><?= h($r['Rooms']) ?></td></tr><?php endforeach; ?></tbody></table></div></div>
<div class="row g-4"><div class="col-lg-6"><div class="data-card"><h5 class="fw-bold mb-3">Room Utilization</h5><div class="table-responsive"><table class="table"><thead><tr><th>Room</th><th>TTD</th><th>Bookings</th><th>Periods</th></tr></thead><tbody><?php foreach($rooms as $r): ?><tr><td><?= h($r['Title']) ?></td><td><?= h($r['TTDName']) ?></td><td><?= h($r['TotalBookings']) ?></td><td><?= h($r['UsedPeriods']) ?></td></tr><?php endforeach; ?></tbody></table></div></div></div><div class="col-lg-6"><div class="data-card"><h5 class="fw-bold mb-3">Class Schedule Summary</h5><div class="table-responsive"><table class="table"><thead><tr><th>Class</th><th>Semester</th><th>Entries</th></tr></thead><tbody><?php foreach($classes as $c): ?><tr><td><?= h($c['Name']) ?></td><td><?= h($c['CurrentSemester']) ?></td><td><?= h($c['TotalEntries']) ?></td></tr><?php endforeach; ?></tbody></table></div></div></div></div>
<?php dashboard_end(); ?>
