<?php
require_once __DIR__ . '/../includes/layout.php';
require_role('student');
$studentId=(int)current_user_id();$student=mysqli_fetch_assoc(mysqli_query($conn,"SELECT * FROM student WHERE StudentID=$studentId"));$semester=mysqli_real_escape_string($conn,$student['Semester'] ?? '');
$entries=fetch_all("SELECT c.Name AS ClassName,p.Title,p.StartTime,p.EndTime,p.FridayStartTime,p.FridayEndTime,d.Days,s.Name AS SubjectName,t.Name AS TeacherName,r.Title AS RoomTitle,d.Notes,d.CellColor FROM timetablecelldetail d JOIN timetablecell cell ON cell.TTCID=d.TTCID JOIN `class` c ON c.ClassID=cell.ClassID JOIN period p ON p.PeriodID=cell.PeriodID LEFT JOIN subject s ON s.SubjectID=d.SubjectID LEFT JOIN teacher t ON t.TeacherID=d.TeacherID LEFT JOIN room r ON r.RoomID=d.RoomID WHERE c.CurrentSemester LIKE '%$semester%' OR s.Semester LIKE '%$semester%' ORDER BY c.Name,p.DisplayOrder,d.DisplayOrder");
dashboard_start('My Timetable','Student academic schedule');
?>
<div class="welcome-card mb-4"><h2 class="fw-bold">Welcome, <?= h(current_user_name()) ?></h2><p class="mb-0 opacity-75">Semester: <?= h($student['Semester'] ?? '-') ?> | Department: <?= h($student['Department'] ?? '-') ?></p></div>
<div class="data-card"><div class="d-flex justify-content-between align-items-center mb-3 no-print"><h5 class="fw-bold mb-0">Class Timetable</h5><button class="btn btn-outline-primary" onclick="window.print()"><i class="fa-solid fa-print me-1"></i>Print</button></div><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Class</th><th>Subject</th><th>Teacher</th><th>Days</th><th>Period</th><th>Time</th><th>Room</th></tr></thead><tbody><?php if(!$entries): ?><tr><td colspan="7" class="text-center text-muted py-4">No timetable found for your semester.</td></tr><?php endif; foreach($entries as $e): ?><tr><td><?= h($e['ClassName']) ?></td><td><span class="color-dot" style="background:<?= h($e['CellColor']) ?>"></span><b><?= h($e['SubjectName']) ?></b></td><td><?= h($e['TeacherName']) ?></td><td class="text-danger fw-bold"><?= h($e['Days']) ?></td><td><?= h($e['Title']) ?></td><td><?= h(format_time_short($e['StartTime']).' - '.format_time_short($e['EndTime'])) ?></td><td><?= h($e['RoomTitle']) ?></td></tr><?php endforeach; ?></tbody></table></div></div>
<?php dashboard_end(); ?>
